/* A configuration object for the webpack-bundle-analyzer plugin. */
module.exports = {
  STATS_CONFIG: {
    stats: {
      all: undefined,
      assets: true,
      builtAt: true,
      cached: false,
      cachedAssets: false,
      children: false,
      chunkGroups: false,
      chunkModules: false,
      chunkOrigins: false,
      chunks: false,
      colors: true,
      depth: false,
      entrypoints: false,
      env: true,
      errorDetails: true,
      errors: true,
      hash: true,
      modules: false,
      performance: true,
      providedExports: false,
      publicPath: true,
      reasons: true,
      source: false,
      timings: true,
      usedExports: false,
      version: true,
      warnings: false,
    },
  },
};
